DROP TABLE IF EXISTS CTRLWS;
CREATE TABLE CTRLWS(
    AUTOSEQUENCIAL numeric,
    IDFILIAL numeric,
    IDUSUARIO numeric,
    USUARIO char,
    IP_ORIGEM char,
    REMESSA numeric,
    MODELO numeric,
    CAIXA numeric,
    LOCALIZADOR numeric,
    IDENTIFICADOR numeric,
    ORIGEM numeric,
    QUANT numeric,
    TM_INI datetime,
    TM_FIM datetime,
    TM_IMP datetime,
    CANCELADO numeric,
    CANCELUSER numeric,
    IMPORTADO numeric,
    BORDERO numeric,
    BANCODEP numeric,
    AGENDEP numeric,
    CONTADEP numeric,
    CODIGODEP numeric,
    FILIALDEP numeric,
    VALOR numeric,
    DADOSAUX varchar,
    SINCRONIZA numeric,
    STATUS numeric,
    ID_LOCK varchar,
    TM_LOCK datetime,
    UUID varchar,
    PRIMARY KEY(AUTOSEQUENCIAL)
);

DROP TABLE IF EXISTS DOCSWS;
CREATE TABLE DOCSWS(
    AUTOSEQUENCIAL numeric,
    IDREMESSA numeric,
    TIPODOC numeric,
    MODELO numeric,
    XMLDOC varchar,
    TM_CAP datetime,
    TIPOIMGF numeric,
    TIPOIMGV numeric,
    DPIIMGF numeric,
    DPIIMGV numeric,
    CERTIFICADA numeric,
    CRIPTOGRAFIA numeric,
    CANCELADO numeric,
    BANCOCMC7 numeric,
    AGENCIACMC7 numeric,
    COMPECMC7 numeric,
    NUMEROCMC7 numeric,
    CONTACMC7 numeric,
    VALOR numeric,
    CPFCNPJ numeric,
    DATAVENC datetime,
    CMC7 char,
    VALOREXT numeric,
    SEQDOCTO numeric,
    STATUS numeric,
    TRANSMITIDO numeric,
    CODNCONF numeric,
    FORMALIZA numeric,
    NSU numeric,
    SEQORIGEM numeric,
    IDENTIFICADOR varchar,
    DATA_EMISSAO datetime,
    CLIENTE_DESDE datetime,
    ID_LOCK numeric,
    UUID_REMESSA varchar,
    PRIMARY KEY(AUTOSEQUENCIAL)
);

DROP TABLE IF EXISTS IMGSWS;
CREATE TABLE IMGSWS(
    IDDOCTO numeric,
    SZF numeric,
    SZV numeric,
    IMGF varbinary,
    IMGV varbinary,
    SZHF numeric,
    SZHV numeric,
    HASHF varbinary,
    HASHV varbinary,
    PRIMARY KEY(IDDOCTO)
);